import java.util.*;

public class TestMyCircularDoubleLinkedList {
	public static void main(String[] args) {
		String[] name1 = { "Tom", "George", "Peter", "Jean", "Jane" };
		String[] name2 = { "George", "Michael", "Michelle", "Daniel" };
		String[] name3 = { "Tom", "Peter", "Jane", "Adam", "Peter", "Mary", "David" };
		Integer[] num1 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 };
		Integer[] num2 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 };
		Integer[] num = { 5, 6, 10, 3, 4, 1, 2, 20 };
		System.out.println("Testing Collection constructor");
		Collection<Integer> num3 = new MyCircularDoubleLinkedList<>(num);
		MyCircularDoubleLinkedList<Integer> c1 = new MyCircularDoubleLinkedList<>(num3);
		System.out.println("c1: " + c1);
		MyCircularDoubleLinkedList<String> c2 = new MyCircularDoubleLinkedList<>(Arrays.asList(name1));
		System.out.println("c2: " + c2 + "\n");
		System.out.println("Testing addLast");
		MyCircularDoubleLinkedList<String> temp = new MyCircularDoubleLinkedList<>();
		for (int i = 0; i < name1.length; i++) {
			temp.addLast(name1[i]);
		}
		System.out.println(temp);
		System.out.println("Testing addLast, add, and add(index,e) ");
		temp.addLast("Bahram");
		temp.addLast("Zartoshty");
		System.out.println("\nTesting add(index,e) and remove(index) ");
		temp.add(1,"****");
		System.out.println(temp);
		temp.add(10,"****");
		temp.remove(1);
		System.out.println(temp);
		temp.remove(10);
		System.out.println("\nTesting remove(object) ");
		System.out.println(temp+" : "+temp.remove("Zartoshty"));
		System.out.println(temp+" : "+temp.remove("Zartoshty"));
		System.out.println("\nTesting reverse()");
		MyCircularDoubleLinkedList<Integer> l = new MyCircularDoubleLinkedList<>(num1);
		System.out.println(l);
		l.reverse();
		System.out.println(l);
		MyCircularDoubleLinkedList<Integer> l1 = new MyCircularDoubleLinkedList<>(num2);
		System.out.println(l1);
		l1.reverse();
		System.out.println(l1);
		MyCircularDoubleLinkedList<Integer> list1 = new MyCircularDoubleLinkedList<>();
		System.out.println("\nTesting addInOrder()"); 
		for (int i = 0; i < num.length; ++i) {
			list1.addInOrder(num[i]);
		}
		System.out.println("list1 " + list1);
		System.out.println("\nTesting overloaded constructor");
		System.out.println("name1; " + Arrays.asList(name1));
		MyCircularDoubleLinkedList<String> list2 = new MyCircularDoubleLinkedList<String>(name1);
		System.out.println("list2: " + list2);
		System.out.println("temp: " + temp);
		System.out.println("\nTesting equlas()");
		System.out.println("list2 equals temp: " + (list2.equals(temp) ? "PASSED" : "FAILED"));
		System.out.println("\nTesting set method");
		System.out.println("temp index 4 was: Jane " + ("Jane".equals(temp.set(4, "Bahram")) ? "PASSED" : "FAILED"));
		System.out.println();
		System.out.println("list2: " + list2);
		System.out.println("temp: " + temp);
		System.out.println("\nTesting equlas()");
		System.out.println("list2 equals temp: " + (list2.equals(temp) ? "PASSED" : "FAILED"));
		MyCircularDoubleLinkedList<String> list3 = new MyCircularDoubleLinkedList<String>(name3);
		System.out.println("\nTesting list1.set(1,100)");
		System.out.println("list1: " + list1);
		list1.set(1, 100);
		System.out.println("list1: " + list1);
		System.out.println("\nTesting list1.set(10,102)");
		System.out.println("list1: " + list1);
		System.out.println("Indedx out of bound: " + (list1.set(10, 102) == null ? "PASSESD" : "FAILED"));
		System.out.println("\nTesting printList() & printReverse()");
		list2.printList();
		System.out.println();
		list2.printReverse();
		System.out.println("\nTesting indexOf(\"Peter\")");
		System.out.println(list3);
		System.out.println("First index of Peter is 1: " + (list3.indexOf("Peter") == 1 ? "PASSED" : "FAILED"));
		System.out.println("First index of Bahram is -1: " + (list3.indexOf("Bahram") == -1 ? "PASSED" : "FAILED"));
		System.out.println("\nTesting lastIndexOf(\"Peter\")");
		System.out.println("Last index of Peter is 4 " + (list3.lastIndexOf("Peter") == 4 ? "PASSED" : "FAILED"));
		System.out.println("Last index of Bahram is -1: " + (list3.lastIndexOf("Bahram") == -1 ? "PASSED" : "FAILED"));
		System.out.println("\nTesting contains()");
		System.out.println("list1 contains 20 is " + list1.contains(20));
		System.out.println("list3 contains Peter is " + list3.contains("Peter"));
		System.out.println("list1 contains 300 is " + list1.contains(300));
		System.out.println("\nTesting getLength()");
		System.out.println(list1);
		System.out.println("Length of list1 is 8 " + (list1.getLength() == 8 ? "PASSED" : "FAILED"));
		System.out.println(list3);
		System.out.println("Length of list3 is 7 " + (list3.getLength() == 7 ? "PASSED" : "FAILED"));
		System.out.println("\nTesting get(2) and get(10)");
		System.out.println(list1);
		System.out.println(list1.get(2));
		System.out.println(list1.get(10));
		System.out.println("\nTesting middleElement()");
		System.out.println(l);
		System.out.println(l.middleElement());
		System.out.println(l1);
		System.out.println(l1.middleElement());
		System.out.println("\nTesting split()");
		System.out.println(list1);
		MyCircularDoubleLinkedList<Integer> list4 = list1.split();
		System.out.println(list1);
		System.out.println(list4);
		MyCircularDoubleLinkedList<String> s1 = new MyCircularDoubleLinkedList<>(name1);
		MyCircularDoubleLinkedList<String> s2 = new MyCircularDoubleLinkedList<>(name2);
		MyCircularDoubleLinkedList<String> s3 = new MyCircularDoubleLinkedList<>(name3);

		// Testing set operations
		System.out.println("\nTesting containAll()");
		System.out.println(s1.containsAll(s1));
		System.out.println(s1.containsAll(s2));
		System.out.println("\nTesting addAll()");
		s1.addAll(s2);
		System.out.println(s1);
		System.out.println("\nTesting retainAll()");
		s1.retainAll(s2);
		System.out.println(s1 + "\n");
		System.out.println("Testing reverseKGroup(4)");
		MyCircularDoubleLinkedList<Integer> s4 = new MyCircularDoubleLinkedList<>(num);
		System.out.println("s4: " + s4);
		s4.reverseKGroup(4);
		System.out.println("s4: " + s4);
		System.out.println("Testing reverseKGroup(3)");
		System.out.println("s4: " + s4);
		s4.reverseKGroup(3);
		System.out.println("s4: " + s4);
		System.out.println("Testing toArray()");
		System.out.println((s4.toArray()!=null) ? Arrays.asList(s4.toArray()):null);
		Integer[] array = new Integer[s4.size()];
		s4.toArray(array);
		System.out.println(Arrays.asList(array));
	}
}